### ISSUE TITLE
Using py-tetrad for Analyzing Health Level Changes in Subjects Under Different Exposure Environments: Controlling for Invariant Factors

### ISSUE THREAD

**Issue by miaomiao-alt** [cmu-phil/py-tetrad#24] opened 2024-06-18 04:13 UTC
Hello,
Our research aims to observe changes in health levels of subjects under different exposure environments. Since we cannot expose the subjects to different environments continuously, we measure their health levels at specific time intervals and compare the data with previous measurements. Therefore, we need to compare multiple data points of the same individual to control for individual differences in the results.
Given our short research period, each subject's baseline information remains unchanged during this time, which can be represented by an ID. To eliminate the influence of these unchanged factors on our results, we use a regression analysis method (using ID as the independent variable and the target variable as the dependent variable to establish a regression model, and then extract the residual data for further analysis), to account for these invariant factors' impact on health levels, allowing us to more accurately assess the effects of exposure environments.
This is the preparation we have done before using py-tetrad for analysis. Can we use any control measures within the py-tetrad library to address the issues mentioned above during the analysis process?
Thank you for your help.
If I'm not clear, you can tell me and I'll rephrase my words.

**Comment by miaomiao-alt** [comment] 2024-06-18 04:18
I have an additional question, how can I be sure that the sample size of our study can meet the requirements of this approach

**Comment by miaomiao-alt** [comment] 2024-06-18 08:33
Sorry, I have one more question. Suppose I have six variables a, b, c, d, e, f, and I set the time constraint abc to tier0 and def to tier1. Do I also need to specify that all ABCs must point to def and that def must not point to abc?

**Comment by miaomiao-alt** [comment] 2024-06-19 01:18
Thank you so much! I have another question. In py-tetrad, what are the sample size requirements of boss algorithm and FGSE algorithm respectively

**Comment by jdramsey** [comment] 2024-06-21 20:53
What do you mean by "sample size requirements"? Do you mean how many samples to you need for a good result? BOSS is a lot better in this regard. Let me get the paper for you (did I send this already? If so, sorry for repeating myself)...

https://proceedings.neurips.cc/paper_files/paper/2023/hash/c9cde817d04811ba28e44071bd9f76a5-Abstract-Conference.html

In this paper you can see in the simulation how accurate BOSS is, compared to PC or FGES. Look at the various figures. BOSS is accurate even for very dense graphs, which other algorithms are not. Thus, BOSS does not need as many samples as these other algorithms to get a good answer.

Can you give me more details on what accuracy measure you're trying to optimize? Do you need accurate adjacencies in the graph? Or accurate arrow endpoints? By accurate, do you mean that you want to make sure you find all of the adjacencies or arrow endpoints you can? Or do you want to make sure that the adjacencies and arrow endpoints give you reliable information (i.e., that there aren't too many extra adjacencies or arrow endpoints in the estimated graph)? I think if I knew more about your requirements I could say something more helpful.

**Comment by jdramsey** [comment] 2024-06-21 20:54
This question I'm not sure how to answer:
`Sorry, I have one more question. Suppose I have six variables a, b, c, d, e, f, and I set the time constraint abc to tier0 and def to tier1. Do I also need to specify that all ABCs must point to def and that def must not point to abc?`

What is def?

**Comment by jdramsey** [comment] 2024-06-21 20:57
For this:
`Hello,
Our research aims to observe changes in health levels of subjects under different exposure environments. Since we cannot expose the subjects to different environments continuously, we measure their health levels at specific time intervals and compare the data with previous measurements. Therefore, we need to compare multiple data points of the same individual to control for individual differences in the results.
Given our short research period, each subject's baseline information remains unchanged during this time, which can be represented by an ID. To eliminate the influence of these unchanged factors on our results, we use a regression analysis method (using ID as the independent variable and the target variable as the dependent variable to establish a regression model, and then extract the residual data for further analysis), to account for these invariant factors' impact on health levels, allowing us to more accurately assess the effects of exposure environments.
This is the preparation we have done before using py-tetrad for analysis. Can we use any control measures within the py-tetrad library to address the issues mentioned above during the analysis process?
Thank you for your help.
If I'm not clear, you can tell me and I'll rephrase my words.`

--yes, can you explain a little better? If you mean, can you run a causal analysis on residual variables to regress out time-dependent changes, the answer is yes; we've done that quite a bit.

**Comment by miaomiao-alt** [comment] 2024-06-24 02:31
thank you so much！Your answer is very useful to me！

**Comment by miaomiao-alt** [comment] 2024-06-24 02:44
I would like to describe my problem in more detail:
 Suppose there are six variables：a, b, c, d, e, f. I want to get a cause-and-effect diagram like the one below. So I have three solutions. Firstly, I set the time constraint abc to tier0 and def to tier1. Secondly, I set Required Edge Constraints(a/b/c to d/e/f) and Required Edge Constraints( d/e/f not to a/b/c). Lastly, not only do I set the time constraint abc to tier0 and def to tier1, but aslo I set the time constraint abc to tier0 and def to tier1.
<img width="297" alt="微信图片_20240624103839" src="https://github.com/cmu-phil/py-tetrad/assets/172348150/42892fcb-2407-426d-aa25-cb8c73b278f3">

**Comment by miaomiao-alt** [comment] 2024-06-24 03:03
I have read this literature and understood the superior performance of BOSS algorithm mentioned in the literature under limited sample size. Therefore, I used the BOSS algorithm to get my preliminary results, but I still have the following questions to ask you:
1. What code can I use to beautify my graphics? They look too messy.
2. The graph I get only shows the causal relationship between them, but I want to extract the effect value (for example, beta value) between some two variables in the dot result. What should I do?
3. Can I extract the part of the graph I need from this complete graph?
4. The second graph is the fitting result of my output model. Is it good or bad?
<img width="942" alt="image" src="https://github.com/cmu-phil/py-tetrad/assets/172348150/d490c8d6-a398-4b6b-b800-fc82509ba2c8">
<img width="229" alt="image" src="https://github.com/cmu-phil/py-tetrad/assets/172348150/f20f39bb-f9cc-4ba8-86bb-89357e5d3b52">

**Comment by miaomiao-alt** [comment] 2024-06-24 03:10
In this model, the variables I use are continuous variables. Can I still use this algorithm if I have both continuous and discrete variables in a model? If not, what method should be used?

**Comment by jdramsey** [comment] 2024-06-24 10:54
You can use it with both continuous and discrete variables, though maybe I should update Tetrad first. I've vveen working on that myself on another project and have fixed a few issues for that. But could I ask first of all, how many discrete variables you have and how many categories are there for each of them? That could matter to accuracy.

**Comment by miaomiao-alt** [comment] 2024-06-24 14:23
there are 61 continuous variables and 16 discrete variables.

**Comment by jdramsey** [comment] 2024-06-24 15:33
How many different values do the discrete variables have?

**Comment by miaomiao-alt** [comment] 2024-06-24 15:33
two

**Comment by jdramsey** [comment] 2024-06-24 15:39
Oh, OK. I'll think about this and get back to you.

**Comment by jdramsey** [comment] 2024-06-24 15:41
Hmm... well, one thing I can say right off the bat is that if the discrete variables are all binary, as you say, then you can include them in a linear (continuous) model so long as you represent the values as 0 and 1. They have to be represented as 0 and 1 though; they can't be any other numbers.

**Comment by miaomiao-alt** [comment] 2024-06-24 16:40
okok，thank you so much！

**Comment by miaomiao-alt** [comment] 2024-06-24 16:40
Can you help me with the above questions? These are very important to me.

**Comment by jdramsey** [comment] 2024-06-24 17:02
It will take me some time, as I'm in the middle of some other work at the moment. I can answer one question right away, though. You had asked whether the score was a good one or not. This is a BIC score; there is no way to know what the score is for the true model since you don't have the true model available. All you can do is to maximize this score. (Scores in Tetrad are "higher is better.") BOSS will generally have done a good job of maximizing this score, but you could try other algorithms if you like and compare the scores.

The theorem (Schwarz) is that the true model will have the highest BIC score. Generally, as I said, what people do in practice is to try to maximize the BIC score.

**Comment by miaomiao-alt** [comment] 2024-06-25 00:04
Well, I appreciate you taking time out of your busy schedule to answer my questions. So, this BIC score refers to its actual value or absolute value, because the BIC of my model is a negative number.

**Comment by jdramsey** [comment] 2024-06-25 03:11
That's the thing--BIC is only a relative number. You can only compare BIC scores for the same dataset or at least datasets of the same size with the same variables. The _true_ model has the highest BIC score (be it positive or negative), but all you can do is compare different models to try to maximize it unless you know the true model, in which case you don't need to do any scoring! Haha :-) It's a logged value, which is why it can be positive or negative--that is, it's (using the Tetrad formula) 2 ln L - c k ln N, where L is the likelihood, n is the sample size, k the number of degrees of freedom, and c a multiplier on the penalty that is typically used, which can be any real number; a good value is 2.

Does that make sense?

It can be very negative or even very positive for a model with many variables since the logged likelihood term sums over the logged likelihoods for each variable.

Here is the Wikipedia article on BIC, where the formula is presented slightly differently:

```
https://en.wikipedia.org/wiki/Bayesian_information_criterion
```

When it comes to BIC scores, it's important to remember that any constant multiple of the formula is acceptable, as the score is only relative, not absolute. However, you do need to keep track of whether a higher (or less negative) score is better or a lower score is better. In the case of Tetrad, a higher score is better. For other software, lower may be better.

**Comment by jdramsey** [comment] 2024-06-25 03:14
As far as beautifying your graphics is concerned, what did you have in mind? Are you an avid user of R? Have you used any of R's myriad tools to make publication-quality graphics? You may need to do some text processing on the output to achieve this...

**Comment by jdramsey** [comment] 2024-06-25 03:15
Python also has some very nice tools.

In general, for a graph this large, making beautiful outputs is challenging. You may not be able to present the graph visually like this.

**Comment by miaomiao-alt** [comment] 2024-06-25 07:59
Can I use the tetrad software to beautify this image？Or is it okay to extract part of the graph from this graph？

**Comment by miaomiao-alt** [comment] 2024-06-25 08:01
The graph I get only shows the causal relationship between them, but I want to extract the effect value (for example, beta value) between some two variables in the dot result. What should I do?It is very important.

**Comment by jdramsey** [comment] 2024-06-25 21:12
^ Of course--you can extract part of the graph. That's a good idea. You can just in the text output include only the edges you want to; the edge numbering is actually not used when the graph is read in. Also, you could use Tetrad to display the graphs, but for a graph wiht this many edge in it, that may not help much. There is a feature in Tetrad called "Display Subgraphs" which can be quite nice though, where you can specify the variable you want to focus on in the graph and then display sugraphs of various sorts around those. That may help you to pick out a subgraph. Would you be interested in that?

**Comment by miaomiao-alt** [comment] 2024-06-26 00:26
yes, I'm very interested!I want to explore!

**Comment by miaomiao-alt** [comment] 2024-06-26 00:26
How about this qustion?The graph I get only shows the causal relationship between them, but I want to extract the effect value (for example, beta value) between some two variables in the dot result. What should I do?It is very important.

**Comment by jdramsey** [comment] 2024-06-26 04:10
That's a actually a somewhat difficult question--estimating the coefficient for one edge. You can do this using regression but need to adjust to all of the backdoor paths--i.e. block all of the backdoor paths in the regression. I just added some tools in the Java interface to accomplish this but haven't moved them to R yet. I suppose I could do that sometime soon...

**Comment by miaomiao-alt** [comment] 2024-06-26 07:18
I don't quite understand this sentence：ou can do this using regression but need to adjust to all of the backdoor paths. Now I just made a linear regression analysis between two variables with causal relationship, but I think the beta value in the regression result can not explain the relationship between the variables in this graph, because in the final analysis, it is still a regression analysis of two variables alone.I would appreciate it if you could give me some other ideas.

**Comment by jdramsey** [comment] 2024-06-26 08:17
Just this issue--see if this makes sense to you. Say your graph is X->Y, X->Z->Y, and you want to know the strength of the edge X->Y. If you simply regress Y on X, you won't get the strength of that edge; you will get the total effect of X on Y through both paths. To get just the strength of the X->Y edge, you need to also condition on Z, breaking that path. Does that make sense?

**Comment by jdramsey** [comment] 2024-06-26 08:20
You may of course only be interested in total effects. But if you had a backdoor path, X<-Z->Y, then without conditioning on Z, you would not even be able to estimate the total effect of X on Y, let along the coefficient for X->Y. Does this make sense?

**Comment by miaomiao-alt** [comment] 2024-06-27 00:19
yes,it is.So, what bothers me is how to get the effect size (β) between the variables?

**Comment by jdramsey** [comment] 2024-08-13 18:42
@miaomiao-alt Can I close this issue?

**Comment by miaomiao-alt** [comment] 2024-08-14 05:53
of course！Thank you so much！

---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 08/14/2024 02:42 |
| To | cmu-phil/py-tetrad ***@***.***> |
| Cc | miaomiao-alt ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [cmu-phil/py-tetrad] Using py-tetrad for Analyzing Health Level Changes in Subjects Under Different Exposure Environments: Controlling for Invariant Factors (Issue #24) |

@miaomiao-alt Can I close this issue?

**Comment by jdramsey** [comment] 2024-08-14 05:59
Great!

**Closed by jdramsey** 2024-08-14 05:59 UTC
